connector:
  name: invalidsplunkforautomation
  identifier: invalidsplunkforautomation
  description: ""
  orgIdentifier: cvng
  projectIdentifier: PRE_QA_Frost
  type: Splunk
  spec:
    splunkUrl: https://splunk.dev.harness.io:8089/
    username: harnessadmin
    accountId: -k53qRQAQ1O7DBLb9ACnjQ
    passwordRef: invalidSplunk
